services:
  regrid:
    image: deutscherwetterdienst/regrid:icon-eu-eps-samples
    container_name: regrid_sample
    environment:
      - OUTPUT_FILE=/data/samples/shared/icon_output.grib2
    volumes:
      - app-volume:/data/samples/shared
  lab:
    image: jupyter:example
    container_name: jupyter_regrid
    build: .
    ports:
      - "9000:1234"
    volumes:
      - /media/mahieron/Austausch/workshops/Docker-Compose/notebooks:/app/notebooks
      - app-volume:/data

volumes:
  app-volume: